# Generated by Django 4.2.14 on 2024-07-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, max_digits=18, verbose_name="transaction's amount"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=18, verbose_name="balance"
            ),
        ),
    ]
