# Generated by Django 4.2.14 on 2024-07-14 11:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_alter_transaction_amount_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="txid",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="txid"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="balance",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="label",
            field=models.CharField(db_index=True, max_length=255, verbose_name="label"),
        ),
    ]
